name: Deploy Node Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
        
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Build Docker Image
        run: docker build -t shuhaib109/auctiongems-server .
        
      - name: Publish Image to Docker Hub
        run: docker push shuhaib109/auctiongems-server:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest  
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        env:
          HOST: your-ec2-public-ip
          USER: ubuntu
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_KEY }} $USER@$HOST << 'EOF'
            # Check if the repository exists
            if [ ! -d "/home/ubuntu/actions-runner-server/.git" ]; then
              echo "Cloning the repository..."
              git clone https://github.com/your-username/your-repository.git /home/ubuntu/actions-runner-server
            fi
            
            # Navigate to the repository directory
            cd /home/ubuntu/actions-runner-server
            
            # Pull the latest changes from GitHub
            git pull origin main
            
            # Build the Docker container
            docker build -t shuhaib109/auctiongems-server .
            
            # Stop and remove the previous container (if exists)
            docker stop auctiongems-server-container || true
            docker rm auctiongems-server-container || true
            
            # Run the new container
            docker run -d -p 8000:8000  --name auctiongems-server-container -e DATABASE_URL=${{ secrets.DATABASE_URL }} shuhaib109/auctiongems-server
            
            # Restart or perform any additional deployment steps
            pm2 restart index
          EOF
