name: CI/CD Pipeline for Node.js

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted  # Specifies the self-hosted runner on your Ubuntu server

    steps:
      # Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js with the specified version
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.11.1' 

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run tests
      - name: Run tests
        run: npm test 

      # Uncomment if you have a build process
      # - name: Build application
      #   run: npm run build

  deploy:
    runs-on: self-hosted  # Runs the deployment step on the self-hosted runner
    needs: build

    steps:
      # Checkout code (if needed, the code should already be present)
      - name: Checkout code
        uses: actions/checkout@v2

      # Deploy the application on the self-hosted Ubuntu instance
      - name: Deploy application
        run: |
          # Change to the repository directory (modify this path as needed)
          cd /path/to/your/repo
          
          # Pull the latest changes
          git pull origin main
          
          # Install dependencies
          npm install
          
          # Restart the application with PM2
          pm2 restart index || pm2 start index.js --name "index"
          
          echo "Deployment completed."
