name: CI/CD Pipeline for Node.js 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js with the specified version
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.11.1' # Set your Node.js version

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run tests
      - name: Run tests
        run: npm test  # Ensure you have tests defined; otherwise, skip this step

      # Uncomment if you have a build process
      # - name: Build application
      #   run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Check out the code again for deployment
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up SSH to connect to the EC2 instance
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # Deploy to EC2
      - name: Deploy to EC2
        env:
          HOST: 16.171.153.46
          USER: ubuntu
          REPO_DIR: /E-commerce
        run: |
          ssh -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
            # Print current directory
            echo "Current Directory: $(pwd)"
            
            # Navigate to the repository directory
            cd E-commerce/
            
            # Print the directory after changing
            echo "Changed to Directory: $(pwd)"
            
            # List files in the current directory
            echo "Files in Directory:"
            ls -la
            
            # Check if the directory is a git repository
            if [ ! -d ".git" ]; then
              echo "Not a Git repository. Exiting."
              exit 1
            fi
            
            # Pull the latest changes from the main branch
            git pull origin main
            
            # Install dependencies
            npm install
            
            # Restart the application
            pm2 restart index
            
            # Print the end message
            echo "Deployment completed."
          EOF