name: Deploy Node Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.1'

      - name: Install Dependencies
        run: |
          npm install

      - name: Run Tests (optional)
        run: |
          npm run test  # Only if you have tests defined

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.EC2_SSH_KEY }} username@your-server-ip << 'EOF'
            cd /path/to/your/project
            git pull origin main
            npm install
            npm run build  # If you need a build step
            pm2 restart your-app-name  # Restart your application with PM2
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          NODE_ENV: production
